# Netlify configuration file

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://apps.scsup.com:9080 http://183.221.24.83:4000; frame-src https://apps.scsup.com:9080; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: https://apps.scsup.com:9080; style-src 'self' 'unsafe-inline'; connect-src 'self' https://apps.scsup.com:9080 http://183.221.24.83:4000; worker-src 'self' blob: data:; img-src 'self' data: https: http:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"